### ISSUE TITLE
Check mkvmerge -J and  mediainfo

### ISSUE THREAD

**Issue by davedoesdev** [davedoesdev/webm-muxer.js#8]
Check their output is as expected on recorded WebM

**Comment by guest271314** [comment]
An example of `mkvmerge -J` output from Chrome `MediaRecorder`

```
$ mkvmerge -J 92nd_Street_Y_May_3_2017_Neil_deGrasse_Tyson_in_conversation_with_Robert_Krulwich.webm
{
  "attachments": [],
  "chapters": [],
  "container": {
    "properties": {
      "container_type": 17,
      "is_providing_timestamps": true,
      "muxing_application": "Chrome",
      "writing_application": "Chrome"
    },
    "recognized": true,
    "supported": true,
    "type": "Matroska"
  },
  "errors": [],
  "file_name": "92nd_Street_Y_May_3_2017_Neil_deGrasse_Tyson_in_conversation_with_Robert_Krulwich.webm",
  "global_tags": [],
  "identification_format_version": 12,
  "track_tags": [],
  "tracks": [
    {
      "codec": "Opus",
      "id": 0,
      "properties": {
        "audio_bits_per_sample": 32,
        "audio_channels": 1,
        "audio_sampling_frequency": 48000,
        "codec_id": "A_OPUS",
        "codec_private_data": "4f707573486561640101000080bb0000000000",
        "codec_private_length": 19,
        "default_track": true,
        "enabled_track": true,
        "forced_track": false,
        "language": "eng",
        "minimum_timestamp": 65000000,
        "number": 1,
        "uid": 27874375346381339
      },
      "type": "audio"
    },
    {
      "codec": "VP8",
      "id": 1,
      "properties": {
        "codec_id": "V_VP8",
        "codec_private_length": 0,
        "default_track": true,
        "display_dimensions": "1280x720",
        "display_unit": 0,
        "enabled_track": true,
        "forced_track": false,
        "language": "eng",
        "minimum_timestamp": 0,
        "number": 2,
        "pixel_dimensions": "1280x720",
        "uid": 34025433275864615
      },
      "type": "video"
    }
  ],
  "warnings": []
}
```

and from webm-muxer.js

```
$ mkvmerge -J "camera (7).webm"
{
  "attachments": [],
  "chapters": [],
  "container": {
    "properties": {
      "container_type": 17,
      "duration": 4799000000,
      "is_providing_timestamps": true,
      "muxing_application": "libwebm-0.3.0.0",
      "writing_application": "WebMLiveMuxer"
    },
    "recognized": true,
    "supported": true,
    "type": "Matroska"
  },
  "errors": [],
  "file_name": "camera (7).webm",
  "global_tags": [],
  "identification_format_version": 12,
  "track_tags": [],
  "tracks": [
    {
      "codec": "VP9",
      "id": 0,
      "properties": {
        "codec_id": "V_VP9",
        "codec_private_length": 0,
        "default_track": true,
        "display_dimensions": "640x480",
        "display_unit": 0,
        "enabled_track": true,
        "forced_track": false,
        "language": "eng",
        "minimum_timestamp": 0,
        "number": 1,
        "pixel_dimensions": "640x480",
        "uid": 33854334744861928
      },
      "type": "video"
    }
  ],
  "warnings": []
}
```

Notice the audio track is not printed.

**Comment by davedoesdev** [comment]
Repro'd

**Comment by davedoesdev** [comment]
This may be a bug in mkvmerge. It doesn't display the Opus audio in https://github.com/chromium/chromium/blob/master/media/test/data/bear-320x240-opus-a_enc-a.webm (for example) either.

**Comment by davedoesdev** [comment]
mkvinfo displays OK:

```
+ EBML head
|+ EBML version: 1
|+ EBML read version: 1
|+ Maximum EBML ID length: 4
|+ Maximum EBML size length: 8
|+ Document type: webm
|+ Document type version: 4
|+ Document type read version: 2
+ Segment: size unknown
|+ Seek head (subentries will be skipped)
|+ Segment information
| + Duration: 00:00:08.003000000
| + Timestamp scale: 1000000
| + Multiplexing application: libwebm-0.3.0.0
| + Writing application: WebMLiveMuxer
|+ Tracks
| + Track
|  + Track number: 1 (track ID for mkvmerge & mkvextract: 0)
|  + Track UID: 59153296666618340
|  + Track type: video
|  + Codec ID: V_VP9
|  + Video track
|   + Pixel width: 1280
|   + Pixel height: 720
|   + Frame rate: 30
| + Track
|  + Track number: 2 (track ID for mkvmerge & mkvextract: 1)
|  + Track UID: 21944668225474101
|  + Track type: audio
|  + Codec ID: A_OPUS
|  + Audio track
|   + Sampling frequency: 48000
|   + Channels: 1
|+ Cues (subentries will be skipped)
|+ Cluster
```

**Comment by davedoesdev** [comment]
Seems to be fixed in mkvmerge v60.0.0:

```
david@david-Latitude-E6440:~/Downloads$ mkvmerge --version
mkvmerge v60.0.0 ('Are We Copies?') 64-bit
david@david-Latitude-E6440:~/Downloads$ mkvinfo camera\ \(2\).webm 
+ EBML head
|+ EBML version: 1
|+ EBML read version: 1
|+ Maximum EBML ID length: 4
|+ Maximum EBML size length: 8
|+ Document type: webm
|+ Document type version: 4
|+ Document type read version: 2
+ Segment: size unknown
|+ Seek head (subentries will be skipped)
|+ Segment information
| + Duration: 00:00:08.003000000
| + Timestamp scale: 1000000
| + Multiplexing application: libwebm-0.3.0.0
| + Writing application: WebMLiveMuxer
|+ Tracks
| + Track
|  + Track number: 1 (track ID for mkvmerge & mkvextract: 0)
|  + Track UID: 59153296666618340
|  + Track type: video
|  + Codec ID: V_VP9
|  + Video track
|   + Pixel width: 1280
|   + Pixel height: 720
|   + Frame rate: 30
| + Track
|  + Track number: 2 (track ID for mkvmerge & mkvextract: 1)
|  + Track UID: 21944668225474101
|  + Track type: audio
|  + Codec ID: A_OPUS
|  + Audio track
|   + Sampling frequency: 48000
|   + Channels: 1
|+ Cues (subentries will be skipped)
|+ Cluster
```

**Comment by guest271314** [comment]
> This may be a bug in mkvmerge.

That is possible. I will file an issue for MKVToolNix.

**Comment by davedoesdev** [comment]
It's fixed in v6.0.0 so no need to file an issue.

**Comment by guest271314** [comment]
`-J` is not fixed on mkvmerge v60.0.0 ('Are We Copies?') 64-bit. The Opus track is not listed in tracks. I already filed the issue https://gitlab.com/mbunkus/mkvtoolnix/-/issues/3178.

**Comment by davedoesdev** [comment]
Yeah strange `mkvinfo` works but `mkvmerge -J` doesn't

**Comment by davedoesdev** [comment]
OK per the mkvtoolnix issue, I need to add private codec data, for Opus and probably for VP9 too.
I can add this generically to the muxer and then need to update the demo to show how to do it from JS for Opus and VP9, which will need some research.

**Comment by guest271314** [comment]
M. Bunkus provided additional information https://gitlab.com/mbunkus/mkvtoolnix/-/issues/3178#note_643673640.

https://github.com/kbumsik/opus-media-recorder source code might be helpful. The Opus track from that implementation is printed by `mkvmerge` and plays on Firefox.

**Comment by guest271314** [comment]
I will probably build a version that does not use WebAssembly and WASM, rather streams input directly to the native applications and streams back STDOUT using WebTransport. For that that commands and options that you pass to libwebm and webmtools will be useful.

**Comment by davedoesdev** [comment]
@guest271314 OK

Also https://android.googlesource.com/platform/frameworks/av/+/master/media/libstagefright/foundation/OpusHeader.cpp

**Comment by davedoesdev** [comment]
Should be fixed by 9b81ec0b914520d4e3cdbeafb2b3d975178b9141 (shows in mkvmerge -J now and I also added seek pre-roll)
